output: single_byte_xor_cipher.cpp
	@g++ single_byte_xor_cipher.cpp -o single_byte_xor_cipher.out
	@./single_byte_xor_cipher.out
	
clean:
	@echo "Apagando arquivos criados pelo Makefile."
	@rm single_byte_xor_cipher.out
