output: finding_key_size.cpp break_repeating_key_xor.cpp
	@g++ finding_key_size.cpp -o finding_key_size.out
	@g++ break_repeating_key_xor.cpp -o break_repeating_key_xor.out
	@./finding_key_size.out
	@./break_repeating_key_xor.out

clean:
	@echo "Apagando arquivos criados pelo Makefile."
	@rm finding_key_size.out
	@rm break_repeating_key_xor.out