output: detect_single_character_xor.cpp
	@g++ detect_single_character_xor.cpp -o detect_single_character_xor.out
	@./detect_single_character_xor.out

clean:
	@echo "Apagando arquivos criados pelo Makefile."
	@rm detect_single_character_xor.out
