output: ascii_string_input.cpp
	@g++ ascii_string_input.cpp -o ascii_string_input.out
	@./ascii_string_input.out

clean:
	@echo "Apagando arquivos criados pelo Makefile."
	@rm ascii_string_input.out

